query getDetailedSubscription($data: GetDetailedSubscriptionInput!) {
  getDetailedSubscription(data: $data) {
    id
    user_id
    challenge_category_id
    short_id
    paid
    amount_paid
    last_payment_id
    amount_to_pay
    created_at
     subscription_status {
          status_description {
            translations {
                     name
                   }
          }
        }
    products_bought {
        id
        value
        quantity
        free_value
        product {
          id
          name
        }
        variation {
          id
          images {
            id
            link
            active
          }
          text
          description
        }
    }
    award_subscription_references {
      award {
        name
        price
      }
    }
    last_payment {
         id
      interest_free_amount
      pix_qrcode
      pix_expiration_date
      created_at
      resource_payment_id
      origin_payment_id
      payment_processor_id
      country_id
      bill_expiration_date
      value
      is_paid
      declined
      returned
      entrance
      processed
      processed
      origin_resource_id
      profile_id
      user_id
      status
      installments
      bill_link
      created_at
      updated_at
      card {
        last_digits
        brand
      }
    }
    products_bought {
      id
      value
      quantity
      variation {
        text
        images {
          id
          link
        }
      }
      product {
        name
        images {
          id
          link
        }
      }
    }
    last_payment {
      value
    }
    category {
      id
      name
      order
    }
    user {
      id
      firstname
      lastname
      date_of_birth
      legal_registry_number
      team_name
      gender
      phone
      city {
        name
        state {
          name
        }
      }

      profile {
        profile_avatar
      }
    }
  }
}
