query showAllChallengesV2(
  $pagination: PaginationInput!
  $data: ShowAllChallengesInput!
) {
  showAllChallengesV2(pagination: $pagination, data: $data) {
    page_info {
      current_page
      offset
      total_item_count
      has_next_page
      has_previous_page
    }
    items {
       id
        eligible_spotlight
        name
        image_avatar
        image_cover
        physical_event
        configuration {
          is_paid
        }
    }
  }
}
