query SubscriptionsWithAwardAlreadyWithdrawn(
  $pagination: PaginationInput!
  $challenge_id: String!
) {
  subscriptionsWithAwardAlreadyWithdrawn(
    pagination: $pagination
    challenge_id: $challenge_id
  ) {
    page_info {
      current_page
      offset
      total_item_count
      has_next_page
      has_previous_page
    }
    subscriptions {
       withdrawal_date
       athlete_identification
       short_id
       category {
          id
          order
          name
        }
       user {
          firstname
          lastname
          profile {
            profile_avatar
         }
      }

    }
  }
}
