mutation changeHealthConnections($data: ChangeHealthConnectionsInput!) {
    changeHealthConnections(data: $data) {
      _id
      user_id
      integrated_with_google_fit
      integrated_with_apple_health
      integrated_with_garmin
      integrated_with_polar
      has_company
      last_upload_google_fit
      last_upload_apple_health
    }
  }
