query GetSubscriptionActivities($data: RetrieveSubscriptionActivitiesInput!){
  getSubscriptionActivities(data: $data) {
    activity_id
    activity {
      id
      name
      distance
      total_elevation_gain
      start_date_local
      start_date
      suspicious
      start_date_local
      duplicated
      moving_time_seconds
      elapsed_time_seconds
      third_party_data_source_slug
    }
  }
}
