query GetUserDataFromCrawledActivity($url: String!) {
  getUserDataFromCrawledActivity(url: $url) {
    name
    avatar
    type
    distance
    time
    elevation
    date
    address
    person_name
    key
  }
}
